apiVersion: v1
kind: Secret
metadata:
  name: {{ include "styio-platform.fullname" . }}-postgres
  labels:
    {{- include "styio-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.postgres.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "styio-platform.fullname" . }}-workgroup
  labels:
    {{- include "styio-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  registration-token: {{ .Values.workgroup.registrationToken | quote }}
