#include "PlatformCloud/PackageRegistry/ControlPlane/RegistryRoutes.hpp"

namespace spio::platform
{

std::vector<RouteSpec> BuildRegistryControlPlaneRoutes()
{
  return {
      {
          .operation_id = "registryStatus",
          .method = HttpMethod::Get,
          .path = "/api/pafio-registry-control/v1/status",
          .internal = true,
      },
      {
          .operation_id = "registryDescriptor",
          .method = HttpMethod::Get,
          .path = "/api/pafio-registry-control/v1/descriptor",
          .internal = true,
      },
      {
          .operation_id = "publishRelease",
          .method = HttpMethod::Post,
          .path = "/api/pafio-registry-control/v1/publish",
          .internal = true,
      },
      {
          .operation_id = "verifyRegistry",
          .method = HttpMethod::Post,
          .path = "/api/pafio-registry-control/v1/verify",
          .internal = true,
      },
      {.operation_id = "getPackage",
       .method = HttpMethod::Get,
       .path = "/api/pafio-registry-control/v1/packages/{namespace}/{name}",
       .internal = true},
      {.operation_id = "listPackageReleases",
       .method = HttpMethod::Get,
       .path = "/api/pafio-registry-control/v1/packages/{namespace}/{name}/releases",
       .internal = true},
      {.operation_id = "getPackageRelease",
       .method = HttpMethod::Get,
       .path = "/api/pafio-registry-control/v1/packages/{namespace}/{name}/releases/{version}",
       .internal = true},
      {.operation_id = "yankPackageRelease",
       .method = HttpMethod::Post,
       .path = "/api/pafio-registry-control/v1/packages/{namespace}/{name}/releases/{version}/yank",
       .internal = true},
      {.operation_id = "unyankPackageRelease",
       .method = HttpMethod::Post,
       .path = "/api/pafio-registry-control/v1/packages/{namespace}/{name}/releases/{version}/unyank",
       .internal = true},
      {.operation_id = "listPackageOwners",
       .method = HttpMethod::Get,
       .path = "/api/pafio-registry-control/v1/packages/{namespace}/{name}/owners",
       .internal = true},
      {.operation_id = "addPackageOwner",
       .method = HttpMethod::Post,
       .path = "/api/pafio-registry-control/v1/packages/{namespace}/{name}/owners",
       .internal = true},
      {.operation_id = "removePackageOwner",
       .method = HttpMethod::Delete,
       .path = "/api/pafio-registry-control/v1/packages/{namespace}/{name}/owners/{owner_id}",
       .internal = true},
      {.operation_id = "createPublishToken",
       .method = HttpMethod::Post,
       .path = "/api/pafio-registry-control/v1/tokens",
       .internal = true},
      {.operation_id = "listPublishTokens",
       .method = HttpMethod::Get,
       .path = "/api/pafio-registry-control/v1/tokens",
       .internal = true},
      {.operation_id = "revokePublishToken",
       .method = HttpMethod::Delete,
       .path = "/api/pafio-registry-control/v1/tokens/{token_id}",
       .internal = true},
      {.operation_id = "listRepositories",
       .method = HttpMethod::Get,
       .path = "/api/pafio-registry-control/v1/repositories",
       .internal = true},
      {.operation_id = "listRepositoryVersions",
       .method = HttpMethod::Get,
       .path = "/api/pafio-registry-control/v1/repositories/{repository_id}/versions",
       .internal = true},
      {.operation_id = "getPublication",
       .method = HttpMethod::Get,
       .path = "/api/pafio-registry-control/v1/publications/{publication_id}",
       .internal = true},
      {.operation_id = "verifyPublication",
       .method = HttpMethod::Post,
       .path = "/api/pafio-registry-control/v1/publications/{publication_id}/verify",
       .internal = true},
      {.operation_id = "listDistributions",
       .method = HttpMethod::Get,
       .path = "/api/pafio-registry-control/v1/distributions",
       .internal = true},
      {.operation_id = "promoteDistribution",
       .method = HttpMethod::Post,
       .path = "/api/pafio-registry-control/v1/distributions/{distribution_id}/promote",
       .internal = true},
      {.operation_id = "rollbackDistribution",
       .method = HttpMethod::Post,
       .path = "/api/pafio-registry-control/v1/distributions/{distribution_id}/rollback",
       .internal = true},
      {.operation_id = "listReleaseChannels",
       .method = HttpMethod::Get,
       .path = "/api/pafio-registry-control/v1/release-channels",
       .internal = true},
      {.operation_id = "rolloutReleaseChannel",
       .method = HttpMethod::Post,
       .path = "/api/pafio-registry-control/v1/release-channels/{channel}/rollout",
       .internal = true},
  };
}

}  // namespace spio::platform
